import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const url = 'https://picsum.photos/v2/list';
  const limit = '10';
  const url2 = 'https://dummyjson.com/products';
  const limit2 = '100';

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Table of contents</h1>
        <br />
        <br />

        <Link href="/accordion">
          <u>Accordion page</u>
        </Link>
        <br />
        <Link href="/randomColor">
          <u>Random Color</u>
        </Link>
        <br />
        <Link href="/stars">
          <u>Stars</u>
        </Link>
        <br />
        <Link href={`/imageSlider?url=${encodeURIComponent(url)}&limit=${limit}`}>
          <u>Image Slider</u>
        </Link>
        <br />
        <Link href="/loadMore">
          <u>Load more</u>
        </Link>
        <br />
        <Link href="/treeView">
          <u>Tree View</u>
        </Link>
        <br />
        <Link href="/lightAndDark">
          <u>Light and Dark mode</u>
        </Link>
        <br />
        <Link href={`/progressBar?url=${encodeURIComponent(url2)}limit=${limit2}`}>
          <u>Progress Bar</u>
        </Link>
        <br />
        <Link href="/customTabs">
          <u>Custom Tabs</u>
        </Link>
        <br />
        <Link href="/modal">
          <u>Modal</u>
        </Link>
        <br />
        <Link href="/githubProfile">
          <u>Github Profile</u>
        </Link>
        <br />
        <Link href="/search-autocomplete">
          <u>Search auto-complete</u>
        </Link>
        <br />
        <Link href="/tic-tac-toe">
          <u>Tic-Tac-Toe!</u>
        </Link>
        <br />
        <Link href="/useFetch">
          <u>Custom Hook</u>
        </Link>
        <br />
        <Link href="/onClickOutside">
          <u>Custom on click outside hook</u>
        </Link>

      </main>
    </>
  );
}
